name: motivo-studio

services:
  motivo-studio-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      PORT: "3001"
      COMPILER_BIN: /usr/local/bin/motivoc
      HOSTNAME: "0.0.0.0"

  motivo-studio-client:
    build:
      context: client
      dockerfile: Dockerfile
      args:
        API_PROXY_URL: http://motivo-studio-server:3001
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      API_PROXY_URL: http://motivo-studio-server:3001
      HOSTNAME: "0.0.0.0"
    depends_on:
      - motivo-studio-server

  motivo-studio-gateway:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - motivo-studio-client
      - motivo-studio-server
