services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      PORT: "3001"
      COMPILER_BIN: /usr/local/bin/dslrc
      HOSTNAME: "0.0.0.0"

  client:
    build:
      context: client
      dockerfile: Dockerfile
      args:
        API_PROXY_URL: http://server:3001
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      API_PROXY_URL: http://server:3001
      HOSTNAME: "0.0.0.0"
    depends_on:
      - server

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - client
      - server
