; Motivo — Lexical grammar
; Notation: `?` optional, `+` one-or-more, `*` zero-or-more, `..` char range.

<whitespace>     ::= (' ' | '\t' | '\r' | '\n')+
<line-comment>   ::= "//" <any-char-except-newline>*
<block-comment>  ::= "/*" <any-char>* "*/"

<keyword> ::= "tempo"   | "signature" | "key"
            | "track"   | "pattern"   | "play"
            | "for"     | "loop"      | "if"  | "else"
            | "int"     | "double"    | "bool" | "note" | "seq" | "chord"
            | "using"   | "from"      | "voice" | "rest"
            | "true"    | "false"

<instrument> ::= "piano" | "guitar" | "bass" | "violin" | "drums"
<drum-note>  ::= "kick"  | "snare"  | "hihat" | "crash"  | "ride"

<digit>     ::= '0'..'9'
<alpha>     ::= 'A'..'Z' | 'a'..'z' | '_'
<alnum>     ::= <alpha> | <digit>

INT         ::= <digit>+
FLOAT       ::= <digit>+ '.' <digit>+
BOOL        ::= "true" | "false"

<pitch>     ::= 'A'..'G'
<acc>       ::= '#' | 'b'
NOTE        ::= <pitch> <acc>? '0'..'8'

IDENT       ::= <alpha> <alnum>*

; Operators & Punctuation
PLUS "+"  | MINUS "-" | STAR "*" | SLASH "/" | PERCENT "%"
EQ "="    | EQEQ "==" | NEQ "!=" | LT "<" | GT ">" | LEQ "<=" | GEQ ">="
AND "&&"  | OR "||"   | NOT "!"  | QUESTION "?"
SEMICOLON ";" | COMMA "," | COLON ":" 
LPAREN "("    | RPAREN ")" 
LBRACKET "["  | RBRACKET "]" 
LBRACE "{"    | RBRACE "}"
